---

- name: Install gaming packages
  dnf: 
    name: "{{ packages | selectattr('dnf', 'default') | map(attribute='dnf') | list }}"
    state: present
  tags:
    - dnf
    - download
    - packages
  become: true

- name: Install gaming flatpaks
  dnf: 
    name: "{{ item }}"
    state: present
  with_items: "{{ packages | selectattr('flatpak', 'default') | map(attribute='flatpak') | list }}"
  tags:
    - flatpak
    - download
    - packages
  become: true
