---
# tasks file for default-tooling

- name: Install default packages
  dnf: 
    name: "{{ packages | union(extended_packages | default([])) | selectattr('dnf', 'defined') | map(attribute='dnf') | list }}"
    state: present
  tags:
    - dnf
    - download
    - packages
  become: true

- name: Install default flatpaks
  flatpak: 
    name: "{{ item }}"
    state: present
  with_items: "{{ packages | union(extended_packages | default([])) | selectattr('flatpak', 'defined') | map(attribute='flatpak') | list }}"
  tags:
    - flatpak
    - download
    - packages
  become: true

- name: Check if compat-ffmpeg package is installed
  package:
    name: compat-ffmpeg28
    state: latest
  check_mode: true
  ignore_errors: true
  register: ffmpeg28_check

- name: Workaround for compat-ffmpeg
  dnf:
    name: "compat-ffmpeg28"
    state: latest
  when:
    - ffmpeg28_check is changed
