---
# tasks file for rpmfusion

- name: Add RPMFusion GPG key
  rpm_key:
    state: present
    key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_distribution_major_version }}"
  tags:
    - rpmfusion
    - dnf
    - gpg-key
    - download
  when:
    - ansible_distribution == "Fedora"
  become: true


- name: Check RPMFusion is installed
  dnf:
    name: "rpmfusion-free-release"
    state: present
  ignore_errors: true
  register: rpmfusion_test
  become: true

- name: Install RPMFusion
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  tags:
    - rpmfusion
    - dnf
    - packages
    - download
  when:
    - ansible_distribution == "Fedora"
    - rpmfusion_test is failed
  become: true
