# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

f27:
  stage: test
  variables:
    GIT_STRATEGY: clone
    distro: fedora
    distro_version: 27
  before_script:
    - 'docker pull ${distro}:${distro_version}'
    - 'docker build --no-cache --rm --file=travis/Dockerfile.${distro}-${distro_version} --tag=${distro}-${distro_version}:ansible travis'
    - 'sed -i "s/True/False/" ansible.cfg'
  script:
    - container_id=$(mktemp)
    - 'docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/:ro ${distro}-${distro_version}:ansible > "${container_id}"'
    - 'docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/full.yml --syntax-check'
    - 'docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/full.yml'
    - >
      docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/full.yml
      | grep -q 'changed=0.*failed=0'
      && (echo 'Idempotence test: pass' && exit 0)
      || (echo 'Idempotence test: fail' && exit 1)
    - 'docker rm -f "$(cat ${container_id})"'

f28:
  stage: test
  variables:
    GIT_STRATEGY: clone
    distro: fedora
    distro_version: 28
  before_script:
    - 'docker pull ${distro}:${distro_version}'
    - 'docker build --no-cache --rm --file=travis/Dockerfile.${distro}-${distro_version} --tag=${distro}-${distro_version}:ansible travis'
    - 'sed -i "s/True/False/" ansible.cfg'
  script:
    - container_id=$(mktemp)
    - 'docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/:ro ${distro}-${distro_version}:ansible > "${container_id}"'
    - 'docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/full.yml --syntax-check'
    - 'docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/full.yml'
    - >
      docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/full.yml
      | grep -q 'changed=0.*failed=0'
      && (echo 'Idempotence test: pass' && exit 0)
      || (echo 'Idempotence test: fail' && exit 1)
    - 'docker rm -f "$(cat ${container_id})"'
