---
- hosts: localhost
  roles:
    - sys-upgrade
    - rpmfusion
    - hardware
    - flathub
    - automated-updates
    - default-tooling
    - gnome-enhancements
    - gnome-connect
    - nautilus
    - nextcloud-client
    - riot
    - vscode
    - powerline
    - brave-browser
    - development
    - development-cloud
    - 3dprinting
    - gaming-utils
    - virtualization
