---
# defaults file for default-tooling

extend_packages: []

packages:
  # Shells & config
  - dnf: python3-dnf-plugin-system-upgrade
  - dnf: dnf-plugins-core
  - dnf: util-linux-user
  - dnf: zsh

  # Shell utils
  - dnf: vim
  - dnf: git
  - dnf: ansible
  - dnf: thefuck
  - dnf: stow

  # Desktop utils
  - dnf: tilix
  - dnf: remmina
  - dnf: vlc
  - dnf: libaacs
  - dnf: thunderbird
  - dnf: thunderbird-enigmail
  - dnf: virt-manager
  - dnf: virt-viewer
  - dnf: telegram-desktop
  - dnf: flatpak

  # Media
  - dnf: gimp
  - dnf: krita
  - dnf: darktable

  # Browsers
  - dnf: firefox
  - dnf: chromium

  # Passwordsaves
  - dnf: keepass
  - dnf: pass

  # Fonts
  - dnf: open-sans-fonts
  - dnf: fontawesome-fonts
  - dnf: fontawesome-fonts-web
  - dnf: xorg-x11-fonts-Type1

  # Dictionaries
  - dnf: hunspell-de
  - dnf: aspell-de
