---
# tasks file for gnome-enhancements 

- name: Install gnome enhancements
  dnf: 
    name: "{{ packages | map(attribute='dnf') | list }}"
    state: present
  tags:
    - dnf
    - download
    - packages
  become: true
