---
# tasks file for gnome-enhancements 

- name: Install gnome enhancements
  dnf: 
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ packages | map(attribute='dnf') | list }}"
  tags:
    - dnf
    - download
    - packages
  become: true
