---
# tasks file for gnome-enhancements 

- name: Check if gnome is installed
  command: echo $DESKTOP_SESSION
  register: gnome_check

- name: "Select tasks for {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
  include_tasks: "{{ distro_file }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  loop_control:
    loop_var: distro_file
  when: gnome_check.stdout.find('gnome') != -1
