---
# tasks file for gnome-enhancements 

- name: Install gnome enhancements
  dnf: 
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ packages | map(attribute='apt') | list }}"
  become: true
