---
# tasks file for eso addons
#

- name: Make sure AddOns directory is in place
  file:
    path: "{{ esoaddons_directory }}"
    state: directory

- name: Get cdn download URL
  shell: "curl -s {{ item.url }} | grep -E -o 'https://cdn.esoui.com/downloads/file(.*).zip' | head -n 1 | sed 's# #%20#g'"
  args:
    executable: /usr/bin/bash
    warn: false
  loop: "{{ esoaddons_addons|flatten(levels=1) }}"
  changed_when: False
  register: cdn_urls

- name: Download latest AddOn from ESOUI
  get_url:
    url: "{{ item.stdout }}"
    dest: /tmp
  loop: "{{ cdn_urls.results|flatten(levels=1) }}"
  register: addon_downloads

- name: Install AddOn
  unarchive:
    src: "{{ item.dest }}"
    dest: "{{ esoaddons_directory }}"
    keep_newer: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop: "{{ addon_downloads.results|flatten(levels=1) }}"
  become: true

- name: Get all installed AddOns
  find:
    paths: "{{ esoaddons_directory }}"
    recurse: no
    file_type: directory
  register: installed_addons

- name: Get all activated AddOns
  find:
    paths: "{{ esoaddons_directory_activated }}"
    recurse: no
    file_type: link
  register: active_addons

- name: Deactivate all AddOns
  file:
    dest: "{{ esoaddons_directory_activated }}/{{ item.path | basename }}"
    state: absent
  loop: "{{ active_addons.files|flatten(levels=1) }}"

- name: Activate AddOn
  file:
    src: "{{ item.path }}"
    dest: "{{ esoaddons_directory_activated }}/{{ item.path | basename }}"
    state: link
  loop: "{{ installed_addons.files|flatten(levels=1) }}"
