---
# tasks file for lenovo carbon 6th gen patch cpu-throttling

- name: Install msr-tools
  dnf:
    name: msr-tools
    state: present
  tags:
    - lenovo
    - carbon
    - 6th
    - patches
    - dnf
    - packages
  become: true

- name: Install CPU-Throttling patch script
  copy:
    src: cpu-throttling.sh
    dest: /usr/local/bin/cpu-throttling.sh
    mode: 0755
  register: cpu_throttling_script
  tags:
    - lenovo
    - carbon
    - 6th
    - patches
  become: true

- name: Install CPU-Throttling systemd service
  when: cpu_throttling_script is succeeded
  copy:
    src: cpu-throttling.service
    dest: /etc/systemd/system/cpu-throttling.service
  register: cpu_throttling_service
  tags:
    - lenovo
    - carbon
    - 6th
    - patches
  become: true

- name: Install CPU-throttling systemd timer
  when: cpu_throttling_service is succeeded
  copy:
    src: cpu-throttling.timer
    dest: /etc/systemd/system/cpu-throttling.timer
  register: cpu_throttling_timer
  tags:
    - lenovo
    - carbon
    - 6th
    - patches
  become: true

- name: Enable CPU-throttling systemd service
  when: cpu_throttling_service is succeeded
  systemd:
    name: cpu-throttling.service
    enabled: yes
    state: started
    daemon_reload: yes
  become: true
  notify: "Throttling patch restart notification"

- name: Enable CPU-throttling systemd timer
  when: cpu_throttling_timer is succeeded
  systemd:
    name: cpu-throttling.timer
    enabled: yes
    state: started
    daemon_reload: yes
  become: true
