---
# tasks file for nautilus

- name: Install nautilus packages
  dnf:
    name: "{{ nautilus_packages | map(attribute='dnf') | list }}"
    state: present
  tags:
    - nautilus
    - dnf
    - download
    - packages
  become: true
