---

- name: Install nvidia driver packages
  dnf: 
    name: akmod-nvidia
    state: present
  tags:
    - dnf
    - download
    - packages
    - drivers
    - vga
  become: true

- name: Install nvidia x11 cuda driver
  dnf: 
    name: xorg-x11-drv-nvidia-cuda
    state: present
  tags:
    - dnf
    - download
    - packages
    - drivers
    - vga
  become: true
