---
# tasks file for Flathub

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  tags:
    - flatpak
  when:
    - ansible_version.major >= 2
    - ansible_version.minor >= 6
  become: true
