---
# defaults file for default-tooling

gamingutils_steam_flatpak_library: "{{ ansible_env.HOME }}/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common"
gamingutils_steam_library: "{{ ansible_env.HOME }}/.local/share/Steam/steamapps/common"

extend_packages: []

packages:
  # Communication
  - flatpak: com.discordapp.Discord
  - flatpak: com.skype.Client
  - flatpak: net.jami.Jami

  # Libraries and Managers
  - dnf: steam
  - dnf: gamehub
  - dnf: lutris

  # Keyboard Drivers
  - dnf: ckb-next # open source corsair gaming utility
