---
# tasks file for gnome sound output device chooser
#

- name: Download gse
  get_url:
    url: "{{ gse_url }}"
    dest: /tmp/sound-output-device-chooser.kgshank.tar.gz

- name: Make sure global gnome extension directory is in place
  file:
    path: "/usr/local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net"
    state: directory
  become: true

- name: Unpack gse as global extension
  unarchive:
    src: /tmp/sound-output-device-chooser.kgshank.tar.gz
    dest: /usr/local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net
    extra_opts:
      - "--strip"
      - "2"
  become: true
