---
# tasks file for gnome-theme-orchis
#

- name: Install dependencies
  dnf:
    name:
      - gtk-murrine-engine
      - gnome-themes-extra
    state: present
  tags:
    - dnf
    - packages
    - download
  become: true

- name: Download Orchis Theme
  git:
    repo: "{{ gnome_theme_orchis_url }}"
    dest: /tmp/Orchis
  tags:
    - git
    - download

- name: Install Orchis Theme globally
  command: /tmp/Orchis/install.sh
  args:
    chdir: /tmp/Orchis
    creates: /usr/share/themes/Orchis
  become: true

- name: Set Orchis Theme as Shell and Application theme
  dconf:
    key: "{{ item }}"
    value: "'Orchis'"
    state: present
  with_items:
    - /org/gnome/shell/extensions/user-theme/name
    - /org/gnome/desktop/interface/gtk-theme
  tags:
    - gnome
    - themes

- name: Install numix circle icon theme
  dnf:
    name: numix-icon-theme-circle
    state: present
  tags:
    - dnf
    - download
    - packages
  become: true

- name: Set numix circle theme
  dconf:
    key: /org/gnome/desktop/interface/icon-theme
    value: "'Numix-Circle'"
    state: present
  tags:
    - gnome
    - themes
