---
# tasks file for sys-upgrade

- name: Install aptitude
  apt:
    name: "aptitude"
    state: present
  tags:
    - apt
    - download
    - packages
  become: true

- name: Upgrade all packages
  apt:
    name: "*"
    state: latest
  tags:
    - apt
    - download
    - packages
  become: true

