---
# tasks file for discord


- name: Disable COPR
  command: "dnf copr disable -y tcg/discord"
  args:
    warn: false
  tags:
    - discord
    - dnf
    - copr
  when:
    - ansible_distribution == "Fedora"
    - ansible_distribution_major_version is version('26', '>')
  become: true

- name: Uninstall legacy discord
  dnf:
    name: Discord-installer
    state: absent
  tags:
    - discord
    - dnf
    - packages
  become: true

- name: Install discord
  flatpak:
    name: com.discordapp.Discord
    state: present
  tags:
    - discord
    - flatpak
    - packages
  become: true
