---

# SASS is only available in the latest package provided through COPR
# use native dnf source otherwise
- block:
  - name: Enable Hugo COPR
    command: "dnf copr enable -y daftaupe/hugo"
    args:
      creates: /etc/yum.repos.d/_copr_daftaupe-hugo.repo
      warn: false
    tags:
      - hugo
      - dnf
      - copr
    when:
      - ansible_distribution == "Fedora"
      - ansible_distribution_major_version > 26
    become: true

  - name: Import GPG key
    rpm_key:
      state: present
      key: "https://copr-be.cloud.fedoraproject.org/results/daftaupe/hugo/pubkey.gpg"
    tags:
      - hugo
      - dnf
      - gpg-key
      - download
    become: true

  when: hugo_sass

- name: Install Hugo
  dnf:
    name: hugo
    state: present
  tags:
    - hugo
    - dnf
    - packages
  become: true