---
# tasks file for tray icons
#

- name: Remove previous version (if present)
  file:
    path: /usr/local/share/gnome-shell/extensions/tray-icons@zhangkaizhao.com
    state: absent
  ignore_errors: yes
  become: true

- name: Download Tray Icons
  get_url:
    url: "{{ trayicons_url }}"
    dest: /tmp/gnome-trayicons.zip

- name: Unpack Tray Icons
  unarchive:
    src: /tmp/gnome-trayicons.zip
    dest: /tmp

- name: Install Tray Icons as global extension
  copy:
    src: /tmp/gnome-shell-extension-tray-icons-4
    dest: /usr/local/share/gnome-shell/extensions/tray-icons@zhangkaizhao.com
    remote_src: true
  become: true
