---
# tasks file for gnome-connect
#

- name: Download gsconnect
  get_url:
    url: "{{ gsconnect_url }}"
    dest: /tmp/gsconnect.andyholmes.github.io.zip

- name: Make sure global gnome extension directory is in place
  file:
    path: "/usr/local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io"
    state: directory
  become: true

- name: Unpack gsconnect as global extension
  unarchive:
    src: /tmp/gsconnect.andyholmes.github.io.zip
    dest: /usr/local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io
  become: true

- name: Install gsconnect nautilus extension
  dnf:
    name: nautilus-gsconnect
    state: present
  become: true
